#!/bin/bash
set -euo pipefail

# ============================================================
# PolkaShield — Revive Solidity Deployment Script
# ============================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
SOL_DIR="$ROOT_DIR/contracts/solidity"

if [ ! -f "$SOL_DIR/package.json" ]; then
  echo "Error: Solidity package not found at $SOL_DIR"
  exit 1
fi

cd "$SOL_DIR"

if [ ! -d node_modules ]; then
  echo "Installing Solidity package dependencies..."
  npm install
fi

echo "Deploying Solidity contracts to configured revive network..."
DEPLOY_OUTPUT="$(npm run deploy:revive 2>&1 | tee /tmp/polkashield-revive-deploy.log)"

INTENT_VERIFIER_ADDR="$(echo "$DEPLOY_OUTPUT" | grep -Eo '"intentVerifier"\s*:\s*"0x[a-fA-F0-9]{40}"' | tail -1 | sed -E 's/.*"(0x[a-fA-F0-9]{40})"/\1/')"
DARK_POOL_ADDR="$(echo "$DEPLOY_OUTPUT" | grep -Eo '"darkPool"\s*:\s*"0x[a-fA-F0-9]{40}"' | tail -1 | sed -E 's/.*"(0x[a-fA-F0-9]{40})"/\1/')"

if [ -z "$INTENT_VERIFIER_ADDR" ] || [ -z "$DARK_POOL_ADDR" ]; then
  echo "Error: Failed to parse deployment output."
  echo "Inspect /tmp/polkashield-revive-deploy.log"
  exit 1
fi

echo "IntentVerifierMock: $INTENT_VERIFIER_ADDR"
echo "DarkPool: $DARK_POOL_ADDR"

FRONTEND_ENV="$ROOT_DIR/frontend/.env.revive"
SOLVER_ENV="$ROOT_DIR/.env.revive.solver"

cat > "$FRONTEND_ENV" <<EOF
# Auto-generated by deploy/deploy_revive_solidity.sh
VITE_DARK_POOL_ADDRESS=$DARK_POOL_ADDR
VITE_VERIFIER_ADDRESS=$INTENT_VERIFIER_ADDR
VITE_EVM_DIRECT_SUBMIT=true
EOF

cat > "$SOLVER_ENV" <<EOF
# Auto-generated by deploy/deploy_revive_solidity.sh
DARK_POOL_ADDRESS=$DARK_POOL_ADDR
VERIFIER_ADDRESS=$INTENT_VERIFIER_ADDR
EOF

echo "Generated: $FRONTEND_ENV"
echo "Generated: $SOLVER_ENV"

echo "Done."
